---
- name: Add files to local repository
  shell: git add .
  args:
    chdir: /root/ansible-201/

- name: Commit changes
  shell: git commit -m "new release"
  args:
    chdir: /root/ansible-201/ 

- name: Push to repo
  shell: git push {{ origin }} master
  args:
    chdir: /root/ansible-201/ 
